/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common.js";

export interface ILockableInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "isLocked"
      | "isLockedUntil"
      | "lock"
      | "lockPermit"
      | "lockedUntil"
      | "supportsInterface",
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Lock" | "LockedBy"): EventFragment;

  encodeFunctionData(
    functionFragment: "isLocked",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "isLockedUntil",
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: "lock", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "lockPermit",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: "lockedUntil",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike],
  ): string;

  decodeFunctionResult(functionFragment: "isLocked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isLockedUntil",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "lock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockPermit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockedUntil",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike,
  ): Result;
}

export namespace LockEvent {
  export type InputTuple = [owner: AddressLike, lockUntil: BigNumberish];
  export type OutputTuple = [owner: string, lockUntil: bigint];
  export interface OutputObject {
    owner: string;
    lockUntil: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LockedByEvent {
  export type InputTuple = [
    owner: AddressLike,
    lockBy: AddressLike,
    lockUntil: BigNumberish,
  ];
  export type OutputTuple = [owner: string, lockBy: string, lockUntil: bigint];
  export interface OutputObject {
    owner: string;
    lockBy: string;
    lockUntil: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ILockable extends BaseContract {
  connect(runner?: ContractRunner | null): ILockable;
  waitForDeployment(): Promise<this>;

  interface: ILockableInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  isLocked: TypedContractMethod<[owner: AddressLike], [boolean], "view">;

  isLockedUntil: TypedContractMethod<
    [owner: AddressLike, until: BigNumberish],
    [boolean],
    "view"
  >;

  lock: TypedContractMethod<[until: BigNumberish], [void], "nonpayable">;

  lockPermit: TypedContractMethod<
    [
      owner: AddressLike,
      lockBy: AddressLike,
      lockUntil: BigNumberish,
      deadline: BigNumberish,
      signature: BytesLike,
    ],
    [void],
    "nonpayable"
  >;

  lockedUntil: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: "isLocked",
  ): TypedContractMethod<[owner: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isLockedUntil",
  ): TypedContractMethod<
    [owner: AddressLike, until: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lock",
  ): TypedContractMethod<[until: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lockPermit",
  ): TypedContractMethod<
    [
      owner: AddressLike,
      lockBy: AddressLike,
      lockUntil: BigNumberish,
      deadline: BigNumberish,
      signature: BytesLike,
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lockedUntil",
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "supportsInterface",
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "Lock",
  ): TypedContractEvent<
    LockEvent.InputTuple,
    LockEvent.OutputTuple,
    LockEvent.OutputObject
  >;
  getEvent(
    key: "LockedBy",
  ): TypedContractEvent<
    LockedByEvent.InputTuple,
    LockedByEvent.OutputTuple,
    LockedByEvent.OutputObject
  >;

  filters: {
    "Lock(address,uint48)": TypedContractEvent<
      LockEvent.InputTuple,
      LockEvent.OutputTuple,
      LockEvent.OutputObject
    >;
    Lock: TypedContractEvent<
      LockEvent.InputTuple,
      LockEvent.OutputTuple,
      LockEvent.OutputObject
    >;

    "LockedBy(address,address,uint48)": TypedContractEvent<
      LockedByEvent.InputTuple,
      LockedByEvent.OutputTuple,
      LockedByEvent.OutputObject
    >;
    LockedBy: TypedContractEvent<
      LockedByEvent.InputTuple,
      LockedByEvent.OutputTuple,
      LockedByEvent.OutputObject
    >;
  };
}
