/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common.js";

export declare namespace IMasterChef {
  export type PoolInfoStruct = {
    lpToken: AddressLike;
    allocPoint: BigNumberish;
    startBlock: BigNumberish;
    endBlock: BigNumberish;
    lastRewardBlock: BigNumberish;
    accRewardPerShare: BigNumberish;
  };

  export type PoolInfoStructOutput = [
    lpToken: string,
    allocPoint: bigint,
    startBlock: bigint,
    endBlock: bigint,
    lastRewardBlock: bigint,
    accRewardPerShare: bigint,
  ] & {
    lpToken: string;
    allocPoint: bigint;
    startBlock: bigint;
    endBlock: bigint;
    lastRewardBlock: bigint;
    accRewardPerShare: bigint;
  };

  export type UserInfoStruct = {
    amount: BigNumberish;
    rewardDebt: BigNumberish;
  };

  export type UserInfoStructOutput = [amount: bigint, rewardDebt: bigint] & {
    amount: bigint;
    rewardDebt: bigint;
  };
}

export interface IMasterPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "WETH"
      | "add"
      | "deposit"
      | "depositPermit"
      | "getBlockRewardPerShare"
      | "getMultiplier"
      | "hasPool"
      | "hasPoolToken"
      | "initialize"
      | "initializePool"
      | "massUpdatePools"
      | "pendingRewards"
      | "poolDeposit"
      | "poolId"
      | "poolIdByTokens"
      | "poolInfo"
      | "poolLength"
      | "poolMint"
      | "poolTokenImplementation"
      | "poolTokens"
      | "poolTransfer"
      | "poolWithdraw"
      | "rewardPerBlock"
      | "rewardToken"
      | "rewardVault"
      | "set"
      | "totalAllocPoint"
      | "updatePool"
      | "updateRewardPerBlock"
      | "userInfo"
      | "withdraw",
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "add",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, boolean],
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "depositPermit",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: "getBlockRewardPerShare",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "getMultiplier",
    values: [BigNumberish, BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "hasPool",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "hasPoolToken",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      boolean,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: "initializePool",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      boolean,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: "massUpdatePools",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRewards",
    values: [BigNumberish, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "poolDeposit",
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: "poolId", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "poolIdByTokens",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "poolInfo",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "poolLength",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "poolMint",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "poolTokenImplementation",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "poolTokens",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "poolTransfer",
    values: [AddressLike, AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "poolWithdraw",
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "rewardPerBlock",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "rewardToken",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "rewardVault",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "set",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, boolean],
  ): string;
  encodeFunctionData(
    functionFragment: "totalAllocPoint",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "updatePool",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "updateRewardPerBlock",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "userInfo",
    values: [BigNumberish, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, BigNumberish],
  ): string;

  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositPermit",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlockRewardPerShare",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMultiplier",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "hasPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasPoolToken",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializePool",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "massUpdatePools",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRewards",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolDeposit",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "poolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolIdByTokens",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "poolInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolLength", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolTokenImplementation",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "poolTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolTransfer",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolWithdraw",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardPerBlock",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardToken",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardVault",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "set", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAllocPoint",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "updatePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateRewardPerBlock",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "userInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export interface IMasterPool extends BaseContract {
  connect(runner?: ContractRunner | null): IMasterPool;
  waitForDeployment(): Promise<this>;

  interface: IMasterPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  WETH: TypedContractMethod<[], [string], "view">;

  add: TypedContractMethod<
    [
      _lpToken: AddressLike,
      _allocPoint: BigNumberish,
      _startBlock: BigNumberish,
      _endBlock: BigNumberish,
      _withUpdate: boolean,
    ],
    [bigint],
    "nonpayable"
  >;

  deposit: TypedContractMethod<
    [_pid: BigNumberish, _amount: BigNumberish],
    [void],
    "payable"
  >;

  depositPermit: TypedContractMethod<
    [
      _pid: BigNumberish,
      _amount: BigNumberish,
      _deadline: BigNumberish,
      _signature: BytesLike,
    ],
    [void],
    "nonpayable"
  >;

  getBlockRewardPerShare: TypedContractMethod<
    [_pid: BigNumberish],
    [bigint],
    "view"
  >;

  getMultiplier: TypedContractMethod<
    [_pid: BigNumberish, _fromBlock: BigNumberish, _toBlock: BigNumberish],
    [bigint],
    "view"
  >;

  hasPool: TypedContractMethod<[_lpToken: AddressLike], [boolean], "view">;

  hasPoolToken: TypedContractMethod<
    [_poolToken: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _owner: AddressLike,
      _WETH: AddressLike,
      _rewardToken: AddressLike,
      _rewardPerBlock: BigNumberish,
      _rewardVault: AddressLike,
      _startBlock: BigNumberish,
      _endBlock: BigNumberish,
      addPool: boolean,
    ],
    [void],
    "nonpayable"
  >;

  initializePool: TypedContractMethod<
    [
      _owner: AddressLike,
      _WETH: AddressLike,
      _poolTokenImplementation: AddressLike,
      _rewardToken: AddressLike,
      _rewardPerBlock: BigNumberish,
      _rewardVault: AddressLike,
      _startBlock: BigNumberish,
      _endBlock: BigNumberish,
      addPool: boolean,
    ],
    [void],
    "nonpayable"
  >;

  massUpdatePools: TypedContractMethod<[], [void], "nonpayable">;

  pendingRewards: TypedContractMethod<
    [_pid: BigNumberish, _user: AddressLike],
    [bigint],
    "view"
  >;

  poolDeposit: TypedContractMethod<
    [_user: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  poolId: TypedContractMethod<[pool: AddressLike], [bigint], "view">;

  poolIdByTokens: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  poolInfo: TypedContractMethod<
    [pid: BigNumberish],
    [IMasterChef.PoolInfoStructOutput],
    "view"
  >;

  poolLength: TypedContractMethod<[], [bigint], "view">;

  poolMint: TypedContractMethod<[_from: AddressLike], [void], "nonpayable">;

  poolTokenImplementation: TypedContractMethod<[], [string], "view">;

  poolTokens: TypedContractMethod<[pid: BigNumberish], [string], "view">;

  poolTransfer: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;

  poolWithdraw: TypedContractMethod<
    [_user: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  rewardPerBlock: TypedContractMethod<[], [bigint], "view">;

  rewardToken: TypedContractMethod<[], [string], "view">;

  rewardVault: TypedContractMethod<[], [string], "view">;

  set: TypedContractMethod<
    [
      _pid: BigNumberish,
      _allocPoint: BigNumberish,
      _startBlock: BigNumberish,
      _endBlock: BigNumberish,
      _withUpdate: boolean,
    ],
    [void],
    "nonpayable"
  >;

  totalAllocPoint: TypedContractMethod<[], [bigint], "view">;

  updatePool: TypedContractMethod<[_pid: BigNumberish], [void], "nonpayable">;

  updateRewardPerBlock: TypedContractMethod<
    [newBlockReward: BigNumberish],
    [void],
    "nonpayable"
  >;

  userInfo: TypedContractMethod<
    [pid: BigNumberish, user: AddressLike],
    [IMasterChef.UserInfoStructOutput],
    "view"
  >;

  withdraw: TypedContractMethod<
    [_pid: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: "WETH",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "add",
  ): TypedContractMethod<
    [
      _lpToken: AddressLike,
      _allocPoint: BigNumberish,
      _startBlock: BigNumberish,
      _endBlock: BigNumberish,
      _withUpdate: boolean,
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit",
  ): TypedContractMethod<
    [_pid: BigNumberish, _amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositPermit",
  ): TypedContractMethod<
    [
      _pid: BigNumberish,
      _amount: BigNumberish,
      _deadline: BigNumberish,
      _signature: BytesLike,
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBlockRewardPerShare",
  ): TypedContractMethod<[_pid: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMultiplier",
  ): TypedContractMethod<
    [_pid: BigNumberish, _fromBlock: BigNumberish, _toBlock: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasPool",
  ): TypedContractMethod<[_lpToken: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasPoolToken",
  ): TypedContractMethod<[_poolToken: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "initialize",
  ): TypedContractMethod<
    [
      _owner: AddressLike,
      _WETH: AddressLike,
      _rewardToken: AddressLike,
      _rewardPerBlock: BigNumberish,
      _rewardVault: AddressLike,
      _startBlock: BigNumberish,
      _endBlock: BigNumberish,
      addPool: boolean,
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initializePool",
  ): TypedContractMethod<
    [
      _owner: AddressLike,
      _WETH: AddressLike,
      _poolTokenImplementation: AddressLike,
      _rewardToken: AddressLike,
      _rewardPerBlock: BigNumberish,
      _rewardVault: AddressLike,
      _startBlock: BigNumberish,
      _endBlock: BigNumberish,
      addPool: boolean,
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "massUpdatePools",
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pendingRewards",
  ): TypedContractMethod<
    [_pid: BigNumberish, _user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "poolDeposit",
  ): TypedContractMethod<
    [_user: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "poolId",
  ): TypedContractMethod<[pool: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "poolIdByTokens",
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "poolInfo",
  ): TypedContractMethod<
    [pid: BigNumberish],
    [IMasterChef.PoolInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "poolLength",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "poolMint",
  ): TypedContractMethod<[_from: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "poolTokenImplementation",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolTokens",
  ): TypedContractMethod<[pid: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "poolTransfer",
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "poolWithdraw",
  ): TypedContractMethod<
    [_user: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rewardPerBlock",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rewardToken",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rewardVault",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "set",
  ): TypedContractMethod<
    [
      _pid: BigNumberish,
      _allocPoint: BigNumberish,
      _startBlock: BigNumberish,
      _endBlock: BigNumberish,
      _withUpdate: boolean,
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalAllocPoint",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updatePool",
  ): TypedContractMethod<[_pid: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRewardPerBlock",
  ): TypedContractMethod<[newBlockReward: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userInfo",
  ): TypedContractMethod<
    [pid: BigNumberish, user: AddressLike],
    [IMasterChef.UserInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw",
  ): TypedContractMethod<
    [_pid: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
