/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from"./extensions/index.js";
export type { extensions };
export type { ERC20Upgradeable } from "./ERC20Upgradeable.js";
