/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20UpgradeableSol from "./ERC20Upgradeable.sol/index.js";
export * as extensions from "./extensions/index.js";
