/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as eip712UpgradeableSol from"./EIP712Upgradeable.sol/index.js";
export type { eip712UpgradeableSol };
